### ISSUE TITLE
Disable Light when using Automation

### ISSUE THREAD

**Issue by lux4rd0** [natekspencer/hacs-pura#34]
### The request

Is there a way to use the Pura service without turning the light on when using automation? I have set up a motion sensor to turn on the light in the timer; however, when it's active at night, I prefer not to have it on. Turning off the light in an automation after the Pura still causes it to flash.

### Which Pura device(s) is this request for?

- [X] Pura 3
- [X] Pura 4
- [ ] Pura Car
- [ ] Other (please specify in the additional information field below)

**Comment by natekspencer** [comment]
Unfortunately this is on the Pura side of things for the timer endpoint.
