### ISSUE TITLE
Not recognizing PURA 4 Hardware

### ISSUE THREAD

**Issue by cloudycloud47** [natekspencer/hacs-pura#38]
### The problem

Integration did not recognize the diffuser device as the Version 4 device but instead as version 3.
Official app sees device as version 4 

### What version of Home Assistant Core are you running?

2023.12.1

### Diagnostics information

[config_entry-pura-0318e21504f52db9eeff2924c1f75592.json.txt](https://github.com/natekspencer/hacs-pura/files/13624355/config_entry-pura-0318e21504f52db9eeff2924c1f75592.json.txt)

**Comment by natekspencer** [comment]
This should be resolved in 0.1.19
