### ISSUE TITLE
Google auth?

### ISSUE THREAD

**Issue by thenoid** [natekspencer/hacs-pura#40]
### The request

Wife set up her pura account using google auth.  Is there a simple way to use her pura account with HA? Do I need to disconnect all the devices and start over?

### Which Pura device(s) is this request for?

- [X] Pura 3
- [ ] Pura 4
- [ ] Pura Car
- [ ] Other (please specify in the additional information field below)

**Comment by natekspencer** [comment]
I would suggest migrating them to an account that doesn't use Google for the authentication. I won't have time to figure out that path anytime soon, if ever, though welcome to have someone else figure it out for me. I'll add a note to the README though to indicate that Google Auth and others are not supported

**Comment by kylerw** [comment]
Use forgot your password and enter your gmail address and you can set a password for the Pura account.
