### ISSUE TITLE
Unknown fragrance code ''

### ISSUE THREAD

**Issue by JackJPowell** [natekspencer/hacs-pura#6]
Unknown fragrance code '' is being logged and asked that I open an issue. 

We currently only have one diffuser installed. Slot 1 Fragrance is correctly being reported. Slot 2 Fragrance says "Fragrance code:" Seems like the warning may be due to the lack of fragrance in slot 2. 

Thanks for the integration! It's working great. :)

**Comment by natekspencer** [comment]
Thanks for that! The app doesn't let you remove a fragrance without installing a new one so that's a scenario I didn't even consider haha.

**Comment by natekspencer** [comment]
This should be handled with v0.1.7

**Comment by JackJPowell** [comment]
What service! I'll pull it in soon and let you know if any other issues crop up. Thanks!
