### ISSUE TITLE
Unknown exception while updating Pura data: 'Pura' object has no attribute 'get_devices_v2'

### ISSUE THREAD

**Issue by NoMacSec** [natekspencer/hacs-pura#77]
### The problem

Have had this error for a bit now. Tried removing integration from HA devices and HACS. Cleared data for the integration. Then, reinstalled integration through HACS. Still getting error and integration does not work.

### What version of Home Assistant Core are you running?

2024.11.3

### Anything in the logs that might be useful?

```txt
This error originated from a custom integration.

Logger: custom_components.pura.coordinator
Source: custom_components/pura/coordinator.py:52
integration: Pura (documentation, issues)
First occurred: 4:47:15 PM (10 occurrences)
Last logged: 4:55:31 PM

Unknown exception while updating Pura data: 'Pura' object has no attribute 'get_devices_v2'
Traceback (most recent call last):
  File "/config/custom_components/pura/coordinator.py", line 52, in _async_update_data
    self.api.get_devices_v2
AttributeError: 'Pura' object has no attribute 'get_devices_v2'. Did you mean: 'get_devices'?
```

**Comment by natekspencer** [comment]
How do you have Home Assistant deployed? It looks like you aren't getting the new pypura library installed.

**Comment by NoMacSec** [comment]
> How do you have Home Assistant deployed? It looks like you aren't getting the new pypura library installed.

Thank you for the fast reply. I am running it in kubernetes using the `homeassistant/home-assistant:latest` image.

**Comment by NoMacSec** [comment]
I did not have `pypura` nor `ruff` installed. After downgrading to `1.1.0` and upgrading to `1.2.0`, I now have those python packages.

```sh
# pip list | grep -E "homeassistant|numpy|PyTurboJPEG|pypura|deepdiff|ical|colorlog|ruff" | sort -fd
anel-pwrctrl-homeassistant       0.0.1.dev2
atomicwrites-homeassistant       1.4.1
colorlog                         6.8.2
deepdiff                         6.7.1
homeassistant                    2024.11.3         /usr/src/homeassistant
ical                             8.2.0
icalendar                        6.0.1
numpy                            1.26.4
pypura                           0.2.0
python-homeassistant-analytics   0.8.0
PyTurboJPEG                      1.7.5
recurring-ical-events            3.3.3
ruff                             0.8.1
```

However, I am still getting the same error. I made sure to restart HA, and I also removed and re-added the pura device. I did not see anything in the logs when I installed the integration with HACS.

**Comment by NoMacSec** [comment]
I was able to resolve the issue. I removed my `/config/deps` folder. This [git issue](https://github.com/linuxserver/docker-homeassistant/issues/118) was similar to errors I saw in my logs. Thanks for you help @natekspencer !
