### ISSUE TITLE
pura.start_timer.

### ISSUE THREAD

**Issue by akalderon** [natekspencer/hacs-pura#9]
This service disappeared in 0.1.8 breaking automations that used it - was that deliberate or a current issue? By the way - Thank you for this great integration albeit now without its most useful automation 😊

**Comment by natekspencer** [comment]
@akalderon are you seeing other errors? On mine, it looks like the api data changed and so all of my devices no longer work.

**Comment by akalderon** [comment]
Now that you mention it… indeed nothing works.  Other than the timer service error everything else seems to not respond but not trigger an error hence why I didn’t notice it. Indeed they other changed the API or changed authentication method or are blocking certain endpoints.

**Comment by natekspencer** [comment]
Fortunately it looks like an easy fix. On the wall devices, they changed key format from snake_case to camelCase (e.g. device_id to deviceId). I'll have to roll out a fix later this evening.

**Comment by akalderon** [comment]
Kinda odd. They probably timed it with an application release and I bet the ones that didn’t update yet are dead in the water until they do.  So much for backward compatibility 

Thanks again. I automated the diffusers throughout the house with your integration and everything is sparkly fresh.  I am having an issue with their app and the car diffusers. Their own app doesn’t read the data correctly yet your integration does.

**Comment by natekspencer** [comment]
I also have the issue with the car diffuser and their app. Wasn't sure if it was just an android issue or not though.

**Comment by akalderon** [comment]
Nope. Same on iOS. I opened a case with them and they claimed it’s working just fine because they had no other reports coming in.  It may be that you and I are the only ones that bought the car version to date 😜

**Comment by natekspencer** [comment]
Release v0.1.9 should address this. I might have missed a couple things, so please be on the lookout in case you see anything funny!

**Comment by akalderon** [comment]
Looks right so far. Will monitor over the next 24 hours and report back. Thx.

**Comment by akalderon** [comment]
Works fine. Occasional disconnect / unavailable every 2-3 hours and it reestablishes communication a couple of minutes later but given that the timer method is back it has no effect ony automations.  

Thank you!
